dist: trusty
sudo: required
language: cpp

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       sudo apt-get install -y libudev-dev g++ qt5-qmake qtbase5-dev libqt5serialport5-dev;
   fi;

compiler:
  - clang
  - gcc

matrix:
  allow_failures:
    - os: osx

os:
  - linux
  - osx

script:
 - qmake -qt=qt5
 - make
