{% plantuml %}
digraph tree {
    nodesep=.1;
    rankdir=LR;
    node [shape=box, style="rounded,filled", width=3, height=0];


    /*
     *  Declare nodes
     */
    node_coreApp [label="Core Application", style="squared", width=0];
    node_ifaceSerialPort [label="Serial Port interface"];
    node_gui [label="Basic GUI (terminal-like)"];
    node_configManagement [label="Configuration File management"];
    node_pluginsManagement [label="Plugins management"];


    /*
     *  Draw horizontal arrows
     */
    pnt_ifaceSerialPort[shape=point];
    pnt_ifaceSerialPort->node_ifaceSerialPort;

    pnt_gui[shape=point];
    pnt_gui->node_gui;

    pnt_configManagement[shape=point];
    pnt_configManagement->node_configManagement;

    pnt_pluginsManagement[shape=point];
    pnt_pluginsManagement->node_pluginsManagement;


    /*
     *  Draw vertical lines
     */
    {
        rank=same;
        node_coreApp->pnt_ifaceSerialPort->pnt_gui->pnt_configManagement->pnt_pluginsManagement[arrowhead=none];
    }
}
{% endplantuml %}
